@startuml
!include style.puml
skinparam ArrowFontStyle plain

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant ":ResultDisplay" as ResultDisplay UI_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> MainWindow : fillInnerParts()
activate MainWindow

MainWindow -> MainWindow : autoShowReminders()
activate MainWindow

MainWindow -> Model : getReminderData()
activate Model
Model --> MainWindow : reminderMessage
deactivate Model

MainWindow -> ResultDisplay : setFeedbackToUser(reminderMessage)
activate ResultDisplay
ResultDisplay --> MainWindow : shows reminders on startup
deactivate ResultDisplay

MainWindow --> MainWindow
deactivate MainWindow

[<-- MainWindow
deactivate MainWindow
@enduml
