@startuml
!include style.puml
skinparam ArrowFontStyle plain

Title View Command - Overall Flow

Actor User as user USER_COLOR
Participant ":UI" as ui UI_COLOR
Participant ":Logic" as logic LOGIC_COLOR
Participant ":Model" as model MODEL_COLOR

user -[USER_COLOR]> ui : "view 1"
activate ui UI_COLOR

ui -[UI_COLOR]> logic : execute("view 1")
activate logic LOGIC_COLOR

logic -[LOGIC_COLOR]> logic : "parse command &\ncreate ViewCommand"
activate logic LOGIC_COLOR_T1
logic --[LOGIC_COLOR]> logic
deactivate logic

logic -[LOGIC_COLOR]> model : getFilteredPersonList()
activate model MODEL_COLOR

model --[MODEL_COLOR]> logic : personList
deactivate model

logic -[LOGIC_COLOR]> logic : "extract person\nat index 1"
activate logic LOGIC_COLOR_T1
logic --[LOGIC_COLOR]> logic
deactivate logic

logic --[LOGIC_COLOR]> ui : CommandResult\nwith person data & showViewWindow flag
deactivate logic

ui -[UI_COLOR]> ui : openViewWindow(personData)
activate ui UI_COLOR_T1
ui --[UI_COLOR]> ui
deactivate ui

ui --[UI_COLOR]> user : display ViewWindow
deactivate ui

@enduml